taxonomy: topic
_id: security
name: Security
shortname: Security
parent: Azure
keywords:
  - security
  - key vault
  - azure information protection
  - azure ddos protection
  - security center
hashtags:
  - "#security"
images:
  - https://smartableai.github.io/microsoft-azure/assets/images/topics/security.jpg
services:
  news: https://smartableai.github.io/microsoft-azure/api/news/security/
  learning: https://smartableai.github.io/microsoft-azure/api/learning/security/
